aes: decrypt.cc encrypt.cc key-type.cc functions.cc hex-type.cc ascii-type.cc aes-128.cc base64-type.cc
	g++ -o aes decrypt.cc encrypt.cc key-type.cc functions.cc  hex-type.cc ascii-type.cc aes-128.cc base64-type.cc --std=c++11
